FROM python:3.9
ENV PYTHONUNBUFFERED=1

RUN mkdir /app
WORKDIR /app

COPY requirements.txt ./
ENV DJANGO_SETTINGS_MODULE=config.settings.local
RUN pip install --upgrade pip && pip install -r requirements.txt
COPY . .

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]