version: "3.9"

services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env.local
#    healthcheck:
#      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
#      timeout: 20s
#      retries: 10

  app:
    image: anam-earth:latest
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: anam-earth
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
#      db:
#        condition: service_completed_successfully


volumes:
    mysql_data: