# Generated by Django 4.0.6 on 2022-07-06 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradient', models.FloatField()),
                ('width', models.FloatField()),
                ('is_stair', models.BooleanField()),
                ('flatness', models.CharField(choices=[('상', '상'), ('중', '중'), ('하', '하')], max_length=255)),
                ('end_pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_roads', to='map.position')),
                ('start_pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_roads', to='map.position')),
            ],
        ),
    ]
