version: "3.9"

services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: anam-earth-db
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - anam_earth_mysql:/var/lib/mysql
    env_file:
      - .env.local
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10

  app:
    image: anam-earth-app:latest
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: anam-earth-app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy


volumes:
    anam_earth_mysql: