version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: anam-earth-backend-prod
    command: gunicorn --bind 0:8000 config.wsgi:application --reload
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
      - ../data:/app/data