# Generated by Django 4.0.6 on 2022-08-12 04:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='노드 이름')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='노드 위치(좌표)')),
            ],
        ),
        migrations.CreateModel(
            name='Arc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertical_distance', models.FloatField(verbose_name='수직 거리')),
                ('horizontal_distance', models.FloatField(verbose_name='수평 거리')),
                ('is_stair', models.BooleanField(verbose_name='계단 여부')),
                ('is_step', models.BooleanField(default=False, verbose_name='단차 여부')),
                ('quality', models.CharField(choices=[('상', '상'), ('중', '중'), ('하', '하')], max_length=255, verbose_name='정성 지표')),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_arcs', to='map.node', verbose_name='끝 노드')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_arcs', to='map.node', verbose_name='시작 노드')),
            ],
        ),
    ]
