# Generated by Django 4.0.6 on 2022-08-27 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_rename_location_node_point_alter_arc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arc',
            name='end_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_arcs', to='map.node', verbose_name='도착 노드'),
        ),
        migrations.AlterField(
            model_name='arc',
            name='start_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_arcs', to='map.node', verbose_name='출발 노드'),
        ),
    ]
