# Generated by Django 4.0.6 on 2022-08-18 07:27

import board.models
import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_comment_id_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=board.models.UserNameField(default=django.utils.timezone.now, error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, verbose_name='작성자 이름'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='username',
            field=board.models.UserNameField(default=datetime.datetime(2022, 8, 18, 7, 27, 37, 209571, tzinfo=utc), error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, verbose_name='작성자 이름'),
            preserve_default=False,
        ),
    ]
