# Generated by Django 4.0.6 on 2022-08-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_comment_created_at_comment_username_post_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(max_length=150, verbose_name='작성자 이름'),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(max_length=150, verbose_name='작성자 이름'),
        ),
    ]
