name: Anam Earth CI/CD

on:
  push:
    branches:
      - 'main'

env:
  REPOSITORY_NAME: anam-earth-backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Create .env.prod for Django
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $file_path
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> $file_path
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> $file_path
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> $file_path
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> $file_path
        env:
          file_path: backend/.env.prod
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPOSITORY_NAME }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPOSITORY_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPOSITORY_NAME }}:buildcache,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      -
        name: Code Deploy
        run: >
          aws deploy create-deployment
          --application-name anam-earth-deploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name anam-earth-deploy-group
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }}